### ISSUE TITLE
UploadEntireFileAsync not functioning anymore

### ISSUE THREAD

**Issue by NMamkegh** [mfilippov/vimeo-dot-net#196]
After Vimeo last API update, UploadEntireFileAsync  function is not working anymore and it throws an error with a developer message

**Comment by shashank-tak** [comment]
Same with me, I am using vimeodotnet version 2.0.0.23 and everything is working fine except  UploadEntireFileAsync functions it throws error with developer message saying: **"developer_message":"The streaming approach is no longer functional.**

**Comment by nesanmano** [comment]
Hi, I am using version 3.2.3 of the ibrary. The upload procedure kicks in but it only creates a placeholder and the file is not being uploaded.

```
 if (string.IsNullOrWhiteSpace(fileToUpload)) return null;






            var ticket = _client.GetUploadTicketAsync(100).Result;
            IUploadRequest resp = null;


            using (var file = new BinaryContent(new FileInfo(fileToUpload).Create(), "video/mp4"))
            {
                var length = file.Data.Length;
                resp = _client.UploadEntireFileAsync(file, length ).Result;
            }

            return GetVideo(resp.ClipId.ToString());
```

**Comment by ferozhussain** [comment]
Hi,
For me the video is getting uploaded but it's ending up as "untitled".
`
 var binaryContent = new BinaryContent("......\\testVideo.mp4");
 vimeoClient.UploadEntireFileAsync(binaryContent).Result
 `

**Comment by nesanmano** [comment]
Hello Ferozhussain. My email id is nesanmano@hotmail.com. Please contact me on Skype because I need your help to upload the videos.  I am just able to create a colored placeholder .  Thanks

**Comment by ferozhussain** [comment]
hi @nesanmano , 
I just looked at your code looks like you are trying to create a token. which is not required at that stage.
you can simply call this below code and make it work.

`
                var binaryContent = new BinaryContent("file path goes here");
                var video = vimeoClient.UploadEntireFileAsync(binaryContent).Result;
`

**Comment by nesanmano** [comment]
Hi @ferozhussain ; Thank you so much it is working. Even thought I did not use the token, I did not understand why it never uploaded successfully. Maybe my call to create which trigger an a file stream was the culprit.

**Comment by Joao98Victor** [comment]
Hi, I'm facing the same problem trying to use UploadEntireFileAsync method.

Error generating upload ticket.\nCode: BadRequest\nMessage: {\"invalid_parameters\":[{\"field\":\"type\",\"error_code\":2552,\"error\":\"The streaming approach is no longer functional. For alternatives, please visit https://developer.vimeo.com/api/upload/videos#understanding-upload-approaches.\",\"developer_message\":\"The streaming approach is no longer functional. For alternatives, please visit https://developer.vimeo.com/api/upload/videos#understanding-upload-approaches.\"}],\"error\":\"You have provided an invalid parameter. Please contact developer of this application.\",\"link\":null,\"developer_message\":\"The parameters passed to this API endpoint didn't pass Vimeo's validation. Please check the invalid_parameters list for more information.\",\"error_code\":2204}

As the error suggests this method is trying to pass an invalid "type" parameter, I tried to figure out what was the error but I haven't had the opportunity to try to open a pull request to solve this question. However I think that the error happens because of the ContinueUploadFileAsync method that is called inside UploadEntireFileAsync method.

**Comment by Vicnovais** [comment]
Hello, I have the same problem: "The streaming approach is no longer functional. For alternatives, please visit https://developer.vimeo.com/api/upload/videos#understanding-upload-approaches."

**Comment by ferozhussain** [comment]
@Joao98Victor @Vicnovais  which version are you using

**Comment by mfilippov** [comment]
If you receive "The streaming approach is no longer functional" you are using old version of the library. Please update to the latest.

**Comment by Joao98Victor** [comment]
After updating to the newer version (3.2.4) it works! Thanks!
