### ISSUE TITLE
Error when retrieving account information

### ISSUE THREAD

**Issue by Tall-Paul** [mfilippov/vimeo-dot-net#20]
Hi, is there any documentation for this library anywhere at all?

I've gone through the test classes to try and figure out how it should be used, and I think I'm doing this right....but I can't get the library to work at all.

Here's my initial attempt at connecting to the API and grabbing the account information:

VimeoDotNet.VimeoClient vc = new VimeoDotNet.VimeoClient(ACCESS_TOKEN);
User account = vc.GetAccountInformation();

I get an error:

An unhandled exception of type 'VimeoDotNet.Exceptions.VimeoApiException' occurred in mscorlib.dll
Additional information: Error retrieving account information.

**Comment by alvesman** [comment]
I don't know why but sync methods are not working.
I just tried:

     VimeoClient vClient = new VimeoClient(AccessToken);
     User account = await vClient.GetAccountInformationAsync();

And it works as expected.

**Comment by scommisso** [comment]
Think it was the result of a previous PR.

Just some history on this, this library was initially built when the new Vimeo API was in early-beta, and there have been a number of breaking changes since then. I've also moved off of the project I was using this for.

If anyone wants to take ownership of this repository, I'd be happy moving it over to a new owner as I don't have the time to maintain it anymore, nor do I any longer have the premium Vimeo Pro account that I had been previously using for testing.

**Comment by Dashron** [comment]
Small note, many breaking changes can be fixed by hard coding the version into the library. New users default to new versions, but can still request old versions.

I believe this library was created during 3.0, so the accept header `    application/vnd.vimeo.*+json;version=3.0` would help.

**Comment by scommisso** [comment]
It looks like we're now defaulting to version 3.2. I'm assuming this can be closed?

**Comment by mahboobcse** [comment]
I am facing same problem.
Can you please help me
