### ISSUE TITLE
.Net Core compatibility

### ISSUE THREAD

**Issue by stefanseidl** [mfilippov/vimeo-dot-net#75]
Are there any plans to make vimeo-dot-net compatible with .Net Core?

**Comment by mfilippov** [comment]
Yes I have plans for that.

**Comment by rleeson24** [comment]
What is the status on this?  I am curious what is not compatible.  I am using .Net Core, but I don't know if the issue I am seeing is due to that or not.  I am seeing the result set just fine, but the awaiting method never returns for the system to continue processing.  If I add a ContinueWith, that process is called and I can access the result data just fine, but with the default code, the awaiting method never continues when the result is set.

**Comment by mfilippov** [comment]
Work in progress.

**Comment by mfilippov** [comment]
@rleeson24 .NET Standart 1.3 support released in 1.0.0.2
