### ISSUE TITLE
optimize response using json filter to get a better rateLimit

### ISSUE THREAD

**Issue by Kanamahk** [mfilippov/vimeo-dot-net#86]
As it is said in the title, I am trying to use json filter to get a better rateLimit which is currently set at 100 in my app, wich is the minimum. I read in the vimeo guide (https://developer.vimeo.com/guidelines/rate-limiting) that it would automaticaly be raised if you use json filter. 
The thing is I do not really know where and what to change in your code to achieve that. So I would greatly appreciate a little bit of help.
(I will probably achieve something on my own but it would require much more time I think --')

Anyway thank you for the great library =).

**Comment by BrahmanandaK** [comment]
Identify what specific fields required from each API calls that you make.
Here is code change for upload api request

Endpoints.cs
public const string VideoFields = "/videos/{clipId}?fields={fields}";

vimeoclient_upload.cs
request.UrlSegments.Add("fields", "uri,complete_uri,ticket_id,upload_link_secure,user,quota");

You will need to change all api requests to add "fields" parameter in order to get higher rate limit.

Good luck...

**Comment by mfilippov** [comment]
@RobMalvern Yes, I not started yet. You can do implement it.

**Comment by mfilippov** [comment]
@Kanamahk API filtering added.
